module.exports.PastebinClient = require("./struct/PastebinClient")
module.exports.PastebinError = require("./struct/PastebinError")
module.exports.Paste = require("./struct/Paste")
module.exports.User = require("./struct/User")
module.exports.PasteStore = require("./struct/stores/PasteStore")
module.exports.UserStore = require("./struct/stores/UserStore")
module.exports.UserPasteStore = require("./struct/stores/UserPasteStore")